var sceneImages = new Object();
sceneImages["start"] = new Array();
sceneImages["start"].push("img/home/start/gast_falling.png");
sceneImages["start"].push("img/home/start/gast2-3.png");
sceneImages["start"].push("img/home/start/boden.png");
sceneImages["start"].push("img/home/start/gast3.png");
sceneImages["start"].push("img/home/start/gast1.png");
sceneImages["start"].push("img/home/start/papier.png");
sceneImages["start"].push("img/home/start/gast2-2.png");
sceneImages["start"].push("img/home/start/gast2-1.png");
sceneImages["vonanachb"] = new Array();
sceneImages["vonanachb"].push("img/home/vonanachb/weltkugel.png");
sceneImages["vonanachb"].push("img/home/vonanachb/auto-voll.png");
sceneImages["vonanachb"].push("img/home/vonanachb/haenger.png");
sceneImages["vonanachb"].push("img/home/vonanachb/auto-leer.png");
sceneImages["vonanachb"].push("img/home/vonanachb/bahn.png");
sceneImages["vonanachb"].push("img/home/vonanachb/papierflieger.png");
sceneImages["vonanachb"].push("img/home/vonanachb/flugzeug.png");
sceneImages["vorort"] = new Array();
sceneImages["vorort"].push("img/home/vorort/auto_leer.png");
sceneImages["vorort"].push("img/home/vorort/auto_voll.png");
sceneImages["vorort"].push("img/home/vorort/auto_leer_tueroffen.png");
sceneImages["vorort"].push("img/home/vorort/gast_krabbeln.png");
sceneImages["vorort"].push("img/home/vorort/strasse.png");
sceneImages["vorort"].push("img/home/vorort/boden.png");
sceneImages["vorort"].push("img/home/vorort/fahrgast-1.png");
sceneImages["vorort"].push("img/home/vorort/fahrgast-2.png");
sceneImages["vorort"].push("img/home/vorort/gleise.png");
sceneImages["vorort"].push("img/home/vorort/tram.png");
sceneImages["unterkunft"] = new Array();
sceneImages["unterkunft"].push("img/home/unterkunft/wecker-klingeln1.png");
sceneImages["unterkunft"].push("img/home/unterkunft/zeiger-klein.png");
sceneImages["unterkunft"].push("img/home/unterkunft/bett-schlafen2.png");
sceneImages["unterkunft"].push("img/home/unterkunft/fallen.png");
sceneImages["unterkunft"].push("img/home/unterkunft/wecker-klingeln2.png");
sceneImages["unterkunft"].push("img/home/unterkunft/bett-kippen.png");
sceneImages["unterkunft"].push("img/home/unterkunft/boden.png");
sceneImages["unterkunft"].push("img/home/unterkunft/zeiger-gross.png");
sceneImages["unterkunft"].push("img/home/unterkunft/bett-erschrecken.png");
sceneImages["unterkunft"].push("img/home/unterkunft/wecker.png");
sceneImages["unterkunft"].push("img/home/unterkunft/bett-schlafen1.png");
sceneImages["unterkunft"].push("img/home/unterkunft/bett.png");
sceneImages["geld"] = new Array();
sceneImages["geld"].push("img/home/geld/sprechblase-gross.png");
sceneImages["geld"].push("img/home/geld/gast-landen.png");
sceneImages["geld"].push("img/home/geld/maid-pointing.png");
sceneImages["geld"].push("img/home/geld/sprechblase-klein.png");
sceneImages["geld"].push("img/home/geld/gast-surprised.png");
sceneImages["geld"].push("img/home/geld/gast-wirbeln1.png");
sceneImages["geld"].push("img/home/geld/tuer_zu.png");
sceneImages["geld"].push("img/home/geld/maid.png");
sceneImages["geld"].push("img/home/geld/gast-answering.png");
sceneImages["geld"].push("img/home/geld/tuer_auf.png");
sceneImages["geld"].push("img/home/geld/boden.png");
sceneImages["geld"].push("img/home/geld/wanne.png");
sceneImages["geld"].push("img/home/geld/table-line.png");
sceneImages["geld"].push("img/home/geld/gast-wirbeln2.png");
sceneImages["geld"].push("img/home/geld/gast-listening.png");
sceneImages["geld"].push("img/home/geld/gast-kippen.png");
sceneImages["location"] = new Array();
sceneImages["location"].push("img/home/location/publikum.png");
sceneImages["location"].push("img/home/location/auto.png");
sceneImages["location"].push("img/home/location/stuhl-leer.png");
sceneImages["location"].push("img/home/location/convoy_dot.png");
sceneImages["location"].push("img/home/location/convoy-map.png");
sceneImages["location"].push("img/home/location/bus.png");
sceneImages["location"].push("img/home/location/convoy_map.png");
sceneImages["location"].push("img/home/location/paar.png");
sceneImages["location"].push("img/home/location/stuhl-mitgast.png");
sceneImages["dresscode"] = new Array();
sceneImages["dresscode"].push("img/home/dresscode/gast-zirkus.png");
sceneImages["dresscode"].push("img/home/dresscode/gast-normal.png");
sceneImages["dresscode"].push("img/home/dresscode/gast-ballerina.png");
sceneImages["dresscode"].push("img/home/dresscode/gast-hase.png");
sceneImages["dresscode"].push("img/home/dresscode/boden.png");
sceneImages["dresscode"].push("img/home/dresscode/outfit-hase.png");
sceneImages["dresscode"].push("img/home/dresscode/outfit-smoking.png");
sceneImages["dresscode"].push("img/home/dresscode/gast-smoking.png");
sceneImages["dresscode"].push("img/home/dresscode/bewegungsstreifen.png");
sceneImages["dresscode"].push("img/home/dresscode/outfit-ballerina.png");
sceneImages["dresscode"].push("img/home/dresscode/outfit-zirkus.png");
sceneImages["traditionen"] = new Array();
sceneImages["traditionen"].push("img/home/traditionen/strumpfband.png");
sceneImages["traditionen"].push("img/home/traditionen/gast-verlegen.png");
sceneImages["traditionen"].push("img/home/traditionen/pustefix.png");
sceneImages["traditionen"].push("img/home/traditionen/bubble-pop.png");
sceneImages["traditionen"].push("img/home/traditionen/blumenstrauss.png");
sceneImages["traditionen"].push("img/home/traditionen/gast-normal.png");
sceneImages["traditionen"].push("img/home/traditionen/bubble.png");
sceneImages["traditionen"].push("img/home/traditionen/gast-faengtpustefix.png");
sceneImages["traditionen"].push("img/home/traditionen/gast-insgesicht.png");
sceneImages["traditionen"].push("img/home/traditionen/gast-machtblasen.png");
sceneImages["mitbringen"] = new Array();
sceneImages["mitbringen"].push("img/home/mitbringen/gast-amboss.png");
sceneImages["mitbringen"].push("img/home/mitbringen/gast-stehlampe.png");
sceneImages["mitbringen"].push("img/home/mitbringen/fliegen-amboss.png");
sceneImages["mitbringen"].push("img/home/mitbringen/fliegen-stehlampe.png");
sceneImages["mitbringen"].push("img/home/mitbringen/blitz.png");
sceneImages["mitbringen"].push("img/home/mitbringen/gast-katze.png");
sceneImages["mitbringen"].push("img/home/mitbringen/gast-werfen.png");
sceneImages["mitbringen"].push("img/home/mitbringen/boden.png");
sceneImages["mitbringen"].push("img/home/mitbringen/gast-buecken.png");
sceneImages["mitbringen"].push("img/home/mitbringen/koffer.png");
sceneImages["mitbringen"].push("img/home/mitbringen/gast-fotografiert.png");
sceneImages["mitbringen"].push("img/home/mitbringen/gast-smoking.png");
sceneImages["mitbringen"].push("img/home/mitbringen/gast-kamera.png");
sceneImages["mitbringen"].push("img/home/mitbringen/fliegen-katze.png");
sceneImages["rsvp"] = new Array();
sceneImages["rsvp"].push("img/home/rsvp/paar-normal.png");
sceneImages["rsvp"].push("img/home/rsvp/paar-happy1.png");
sceneImages["rsvp"].push("img/home/rsvp/paar-sad2.png");
sceneImages["rsvp"].push("img/home/rsvp/paar-smile.png");
sceneImages["rsvp"].push("img/home/rsvp/boden.png");
sceneImages["rsvp"].push("img/home/rsvp/paar-sad1.png");
sceneImages["rsvp"].push("img/home/rsvp/paar-happy2.png");
sceneImages["kontakt"] = new Array();
sceneImages["kontakt"].push("img/home/kontakt/paar-winken2.png");
sceneImages["kontakt"].push("img/home/kontakt/noten.png");
sceneImages["kontakt"].push("img/home/kontakt/buehne.png");
sceneImages["kontakt"].push("img/home/kontakt/vofely1.png");
sceneImages["kontakt"].push("img/home/kontakt/vofely2.png");
sceneImages["kontakt"].push("img/home/kontakt/paar-kuessen1.png");
sceneImages["kontakt"].push("img/home/kontakt/paar-winken1.png");
sceneImages["kontakt"].push("img/home/kontakt/paar-kuessen2.png");
sceneImages["kontakt"].push("img/home/kontakt/paar-mittelefon.png");
